stages:
  - test
  - build_static_assets
  - deploy

.js:
  image: node:15
  before_script:
    - git --version
    - node --version
    - npm --version
    - yarn --version
    - yarn

test:
  stage: test
  extends: .js
  script:
    - yarn test

build_static_assets:
  only:
    refs:
      - main
  extends: .js
  stage: build_static_assets
  script:
    - yarn build
  artifacts:
    paths:
      - .out/

deploy:
  only:
    refs:
      - main
  stage: deploy
  script:
    - apk add --no-cache git
    - git config --global credential.helper cache
    - git config --global user.email "uniprotci@gmail.com"
    - git config --global user.name "UniProt CI"
    - git clone --single-branch --branch gh-pages https://uniprotci:${GITHUB_PAT_REPO}@github.com/ebi-uniprot/franklin-sites.git
    - rm franklin-sites/*
    - cp -r .out/* franklin-sites
    - cd franklin-sites
    - git add -A
    - git commit -m "Deploy gitlab.ebi.ac.uk/uniprot/uniprot-website/franklin-sites to github.com/ebi-uniprot/franklin-sites.git:gh-pages"
    - git push origin gh-pages
